data_ingestion:
  bucket_name : "oppe_1"
  project_id : "project-9b8dd2a1-dbd5-49ac-9bc"
  bucket_filename : "data/raw/iris.csv"
  train_ratio : 0.8
  bq_dataset : "iris_dataset"
  bq_table : "iris_table"
  feast_repo_path: "feast-repo/feature_repo"
  schema:
        - name: "sepal_length"
          type: "FLOAT64"
    
        - name: "sepal_width"
          type: "FLOAT64"
    
        - name: "petal_length"
          type: "FLOAT64"
    
        - name: "petal_width"
          type: "FLOAT64"
    
        - name: "species"
          type: "STRING"
        
        - name: "iris_id"
          type: "STRING"

        - name: "event_timestamp"
          type: "DATE"

data_processing:
  categorical_columns: 

  numerical_columns:
   - sepal_length
   - sepal_width
   - petal_length
   - petal_width

  no_of_features : 4

  